module Forest::Hpack
  module StaticTable
    VALUE = [
      {":authority", String.new},
      {":method", "GET"},
      {":method", "POST"},
      {":path", "/"},
      {":path", "/index.html"},
      {":scheme", "http"},
      {":scheme", "https"},
      {":status", "200"},
      {":status", "204"},
      {":status", "206"},
      {":status", "304"},
      {":status", "400"},
      {":status", "404"},
      {":status", "500"},
      {"accept-charset", String.new},
      {"accept-encoding", "gzip, deflate"},
      {"accept-language", String.new},
      {"accept-ranges", String.new},
      {"accept", String.new},
      {"access-control-allow-origin", String.new},
      {"age", String.new},
      {"allow", String.new},
      {"authorization", String.new},
      {"cache-control", String.new},
      {"content-disposition", String.new},
      {"content-encoding", String.new},
      {"content-language", String.new},
      {"content-length", String.new},
      {"content-location", String.new},
      {"content-range", String.new},
      {"content-type", String.new},
      {"cookie", String.new},
      {"date", String.new},
      {"etag", String.new},
      {"expect", String.new},
      {"expires", String.new},
      {"from", String.new},
      {"host", String.new},
      {"if-match", String.new},
      {"if-modified-since", String.new},
      {"if-none-match", String.new},
      {"if-range", String.new},
      {"if-unmodified-since", String.new},
      {"last-modified", String.new},
      {"link", String.new},
      {"location", String.new},
      {"max-forwards", String.new},
      {"proxy-authenticate", String.new},
      {"proxy-authorization", String.new},
      {"range", String.new},
      {"referer", String.new},
      {"refresh", String.new},
      {"retry-after", String.new},
      {"server", String.new},
      {"set-cookie", String.new},
      {"strict-transport-security", String.new},
      {"transfer-encoding", String.new},
      {"user-agent", String.new},
      {"vary", String.new},
      {"via", String.new},
      {"www-authenticate", String.new},
    ]

    SIZE = VALUE.size
  end
end
